export const TIPS_LIST_REQUEST = 'TIPS_LIST_REQUEST'
export const TIPS_LIST_SUCCESS = 'TIPS_LIST_SUCCESS'
export const TIPS_LIST_FAIL = 'TIPS_LIST_FAIL'

export const TIPS_CREATE_REQUEST = 'TIPS_CREATE_REQUEST'
export const TIPS_CREATE_SUCCESS = 'TIPS_CREATE_SUCCESS'
export const TIPS_CREATE_FAIL = 'TIPS_CREATE_FAIL'
export const TIPS_CREATE_RESET = 'TIPS_CREATE_RESET'
